/**
 * File name : PredeterminedTables.c
 * Author : Soo Fatt
 * Date : 26/12/2014
 *
 * References:
 * [1] ITU-T81 Recommendation
 *     Table K.3 Table for luminance DC coefficient differences (pg. 149)
 * [2] ITU-T81 Recommendation
 *     Table K.4 Table for chrominance DC coefficient differences (pg. 149)
 * [3] ITU-T81 Recommendation
 *     Table K.5 Table for luminance AC coefficient differences (pg. 150-153)
 * [4] ITU-T81 Recommendation
 *     Table K.6 Table for chrominance AC coefficient differences (pg. 154-157)
 *
 */

#include "CodeTable.h"
#include "PredeterminedTables.h"
#include "dataType.h"

/*  dcLuminanceTable, dcChrominanceTable, acLuminanceTable, acChrominanceTable
 *  are predetermined Huffman Tables obtained from [1],[2],[3],[4].
 *
 *  DCLumTable, DCChromTable, ACLumTable, ACChromTable
 *  are tables created based on the predetermined tables but are 
 *  rearranged based on code length instead of run/size.
 */
 
RunSizeCode DCLumTable[12] = {{.type = RUNSIZECODE, .runSize = 0x00, .codeLength = 2},
                              {.type = RUNSIZECODE, .runSize = 0x01, .codeLength = 3},
                              {.type = RUNSIZECODE, .runSize = 0x02, .codeLength = 3},
                              {.type = RUNSIZECODE, .runSize = 0x03, .codeLength = 3},
                              {.type = RUNSIZECODE, .runSize = 0x04, .codeLength = 3},
                              {.type = RUNSIZECODE, .runSize = 0x05, .codeLength = 3},
                              {.type = RUNSIZECODE2, .runSize = 0x06, .codeLength = 4},
                              {.type = CODETABLE, .runSize = 0x07, .codeLength = 5},
                              {.type = RUNSIZECODE, .runSize = 0x08, .codeLength = 6},
                              {.type = RUNSIZECODE, .runSize = 0x09, .codeLength = 7},
                              {.type = RUNSIZECODE, .runSize = 0x0A, .codeLength = 8},
                              {.type = CODETABLE, .runSize = 0x0B, .codeLength = 9}};
                              
RunSizeCode DCChromTable[12] = {{.type = RUNSIZECODE, .runSize = 0x00, .codeLength = 2},
                                {.type = RUNSIZECODE, .runSize = 0x01, .codeLength = 2},
                                {.type = RUNSIZECODE, .runSize = 0x02, .codeLength = 2},
                                {.type = RUNSIZECODE, .runSize = 0x03, .codeLength = 3},
                                {.type = RUNSIZECODE, .runSize = 0x04, .codeLength = 4},
                                {.type = CODETABLE, .runSize = 0x05, .codeLength = 5},
                                {.type = RUNSIZECODE, .runSize = 0x06, .codeLength = 6},
                                {.type = RUNSIZECODE, .runSize = 0x07, .codeLength = 7},
                                {.type = RUNSIZECODE, .runSize = 0x08, .codeLength = 8},
                                {.type = CODETABLE, .runSize = 0x09, .codeLength = 9},
                                {.type = RUNSIZECODE, .runSize = 0x0A, .codeLength = 10},
                                {.type = RUNSIZECODE, .runSize = 0x0B, .codeLength = 11}};

RunSizeCode ACLumTable[162] = {{.type = RUNSIZECODE, .runSize = 0x01, .codeLength = 2},
                               {.type = RUNSIZECODE, .runSize = 0x02, .codeLength = 2},
                               {.type = RUNSIZECODE, .runSize = 0x03, .codeLength = 3},
                               {.type = RUNSIZECODE, .runSize = 0x00, .codeLength = 4},
                               {.type = RUNSIZECODE, .runSize = 0x04, .codeLength = 4},
                               {.type = RUNSIZECODE, .runSize = 0x11, .codeLength = 4},
                               {.type = CODETABLE, .runSize = 0x05, .codeLength = 5},
                               {.type = RUNSIZECODE, .runSize = 0x12, .codeLength = 5},
                               {.type = CODETABLE, .runSize = 0x21, .codeLength = 5},
                               {.type = RUNSIZECODE, .runSize = 0x31, .codeLength = 6},
                               {.type = RUNSIZECODE, .runSize = 0x41, .codeLength = 6},
                               {.type = CODETABLE, .runSize = 0x06, .codeLength = 7},
                               {.type = RUNSIZECODE, .runSize = 0x13, .codeLength = 7},
                               {.type = RUNSIZECODE, .runSize = 0x51, .codeLength = 7},
                               {.type = RUNSIZECODE, .runSize = 0x61, .codeLength = 7},
                               {.type = RUNSIZECODE, .runSize = 0x07, .codeLength = 8},
                               {.type = RUNSIZECODE, .runSize = 0x22, .codeLength = 8},
                               {.type = RUNSIZECODE, .runSize = 0x71, .codeLength = 8},
                               {.type = CODETABLE, .runSize = 0x14, .codeLength = 9},
                               {.type = RUNSIZECODE, .runSize = 0x32, .codeLength = 9},
                               {.type = CODETABLE, .runSize = 0x81, .codeLength = 9},
                               {.type = RUNSIZECODE, .runSize = 0x91, .codeLength = 9},
                               {.type = CODETABLE, .runSize = 0xA1, .codeLength = 9},
                               {.type = RUNSIZECODE, .runSize = 0x08, .codeLength = 10},
                               {.type = RUNSIZECODE, .runSize = 0x23, .codeLength = 10},
                               {.type = CODETABLE, .runSize = 0x42, .codeLength = 10},
                               {.type = RUNSIZECODE, .runSize = 0xB1, .codeLength = 10},
                               {.type = RUNSIZECODE, .runSize = 0xC1, .codeLength = 10},
                               {.type = RUNSIZECODE, .runSize = 0x15, .codeLength = 11},
                               {.type = RUNSIZECODE, .runSize = 0x52, .codeLength = 11},
                               {.type = CODETABLE, .runSize = 0xD1, .codeLength = 11},
                               {.type = RUNSIZECODE, .runSize = 0xF0, .codeLength = 11},
                               {.type = RUNSIZECODE, .runSize = 0x24, .codeLength = 12},
                               {.type = RUNSIZECODE, .runSize = 0x33, .codeLength = 12},
                               {.type = RUNSIZECODE, .runSize = 0x62, .codeLength = 12},
                               {.type = RUNSIZECODE, .runSize = 0x72, .codeLength = 12},
                               {.type = CODETABLE, .runSize = 0x82, .codeLength = 15},
                               {.type = RUNSIZECODE, .runSize = 0x09, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x0A, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x16, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x17, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x18, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x19, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x1A, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x25, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x26, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x27, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x28, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x29, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x2A, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x34, .codeLength = 16},
                               {.type = CODETABLE, .runSize = 0x35, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x36, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x37, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x38, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x39, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x3A, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x43, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x44, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x45, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x46, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x47, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x48, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x49, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x4A, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x53, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x54, .codeLength = 16},
                               {.type = CODETABLE, .runSize = 0x55, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x56, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x57, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x58, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x59, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x5A, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x63, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x64, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x65, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x66, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x67, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x68, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x69, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x6A, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x73, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x74, .codeLength = 16},
                               {.type = CODETABLE, .runSize = 0x75, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x76, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x77, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x78, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x79, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x7A, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x83, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x84, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x85, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x86, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x87, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x88, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x89, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x8A, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x92, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x93, .codeLength = 16},
                               {.type = CODETABLE, .runSize = 0x94, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x95, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x96, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x97, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x98, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x99, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0x9A, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xA2, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xA3, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xA4, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xA5, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xA6, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xA7, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xA8, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xA9, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xAA, .codeLength = 16},
                               {.type = CODETABLE, .runSize = 0xB2, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xB3, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xB4, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xB5, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xB6, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xB7, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xB8, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xB9, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xBA, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xC2, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xC3, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xC4, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xC5, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xC6, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xC7, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xC8, .codeLength = 16},
                               {.type = CODETABLE, .runSize = 0xC9, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xCA, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xD2, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xD3, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xD4, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xD5, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xD6, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xD7, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xD8, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xD9, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xDA, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xE1, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xE2, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xE3, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xE4, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xE5, .codeLength = 16},
                               {.type = CODETABLE, .runSize = 0xE6, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xE7, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xE8, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xE9, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xEA, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xF1, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xF2, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xF3, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xF4, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xF5, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xF6, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xF7, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xF8, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xF9, .codeLength = 16},
                               {.type = RUNSIZECODE, .runSize = 0xFA, .codeLength = 16}};

RunSizeCode ACChromTable[162] = {{.type = RUNSIZECODE, .runSize = 0x00, .codeLength = 2},
                                 {.type = RUNSIZECODE, .runSize = 0x01, .codeLength = 2},
                                 {.type = RUNSIZECODE, .runSize = 0x02, .codeLength = 3},
                                 {.type = RUNSIZECODE, .runSize = 0x03, .codeLength = 4},
                                 {.type = RUNSIZECODE, .runSize = 0x11, .codeLength = 4},
                                 {.type = CODETABLE, .runSize = 0x04, .codeLength = 5},
                                 {.type = RUNSIZECODE, .runSize = 0x05, .codeLength = 5},
                                 {.type = CODETABLE, .runSize = 0x21, .codeLength = 5},
                                 {.type = RUNSIZECODE, .runSize = 0x31, .codeLength = 5},
                                 {.type = CODETABLE, .runSize = 0x06, .codeLength = 6},
                                 {.type = RUNSIZECODE, .runSize = 0x12, .codeLength = 6},
                                 {.type = RUNSIZECODE, .runSize = 0x41, .codeLength = 6},
                                 {.type = RUNSIZECODE, .runSize = 0x51, .codeLength = 6},
                                 {.type = CODETABLE, .runSize = 0x07, .codeLength = 7},
                                 {.type = RUNSIZECODE, .runSize = 0x61, .codeLength = 7},
                                 {.type = RUNSIZECODE, .runSize = 0x71, .codeLength = 7},
                                 {.type = RUNSIZECODE, .runSize = 0x13, .codeLength = 8},
                                 {.type = RUNSIZECODE, .runSize = 0x22, .codeLength = 8},
                                 {.type = RUNSIZECODE, .runSize = 0x32, .codeLength = 8},
                                 {.type = RUNSIZECODE, .runSize = 0x81, .codeLength = 8},
                                 {.type = CODETABLE, .runSize = 0x08, .codeLength = 9},
                                 {.type = RUNSIZECODE, .runSize = 0x14, .codeLength = 9},
                                 {.type = CODETABLE, .runSize = 0x42, .codeLength = 9},
                                 {.type = RUNSIZECODE, .runSize = 0x91, .codeLength = 9},
                                 {.type = CODETABLE, .runSize = 0xA1, .codeLength = 9},
                                 {.type = RUNSIZECODE, .runSize = 0xB1, .codeLength = 9},
                                 {.type = CODETABLE, .runSize = 0xC1, .codeLength = 9},
                                 {.type = RUNSIZECODE, .runSize = 0x09, .codeLength = 10},
                                 {.type = RUNSIZECODE, .runSize = 0x23, .codeLength = 10},
                                 {.type = CODETABLE, .runSize = 0x33, .codeLength = 10},
                                 {.type = RUNSIZECODE, .runSize = 0x52, .codeLength = 10},
                                 {.type = RUNSIZECODE, .runSize = 0xF0, .codeLength = 10},
                                 {.type = RUNSIZECODE, .runSize = 0x15, .codeLength = 11},
                                 {.type = RUNSIZECODE, .runSize = 0x62, .codeLength = 11},
                                 {.type = CODETABLE, .runSize = 0x72, .codeLength = 11},
                                 {.type = RUNSIZECODE, .runSize = 0xD1, .codeLength = 11},
                                 {.type = RUNSIZECODE, .runSize = 0x0A, .codeLength = 12},
                                 {.type = RUNSIZECODE, .runSize = 0x16, .codeLength = 12},
                                 {.type = RUNSIZECODE, .runSize = 0x24, .codeLength = 12},
                                 {.type = RUNSIZECODE, .runSize = 0x34, .codeLength = 12},
                                 {.type = CODETABLE, .runSize = 0xE1, .codeLength = 14},
                                 {.type = RUNSIZECODE, .runSize = 0x25, .codeLength = 15},
                                 {.type = RUNSIZECODE, .runSize = 0xF1, .codeLength = 15},
                                 {.type = RUNSIZECODE, .runSize = 0x17, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x18, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x19, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x1A, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x26, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x27, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x28, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x29, .codeLength = 16},
                                 {.type = CODETABLE, .runSize = 0x2A, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x35, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x36, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x37, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x38, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x39, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x3A, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x43, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x44, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x45, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x46, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x47, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x48, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x49, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x4A, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x53, .codeLength = 16},
                                 {.type = CODETABLE, .runSize = 0x54, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x55, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x56, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x57, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x58, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x59, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x5A, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x63, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x64, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x65, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x66, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x67, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x68, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x69, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x6A, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x73, .codeLength = 16},
                                 {.type = CODETABLE, .runSize = 0x74, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x75, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x76, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x77, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x78, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x79, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x7A, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x82, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x83, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x84, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x85, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x86, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x87, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x88, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x89, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x8A, .codeLength = 16},
                                 {.type = CODETABLE, .runSize = 0x92, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x93, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x94, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x95, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x96, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x97, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x98, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x99, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0x9A, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xA2, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xA3, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xA4, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xA5, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xA6, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xA7, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xA8, .codeLength = 16},
                                 {.type = CODETABLE, .runSize = 0xA9, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xAA, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xB2, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xB3, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xB4, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xB5, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xB6, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xB7, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xB8, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xB9, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xBA, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xC2, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xC3, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xC4, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xC5, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xC6, .codeLength = 16},
                                 {.type = CODETABLE, .runSize = 0xC7, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xC8, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xC9, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xCA, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xD2, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xD3, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xD4, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xD5, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xD6, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xD7, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xD8, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xD9, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xDA, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xE2, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xE3, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xE4, .codeLength = 16},
                                 {.type = CODETABLE, .runSize = 0xE5, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xE6, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xE7, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xE8, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xE9, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xEA, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xF2, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xF3, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xF4, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xF5, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xF6, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xF7, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xF8, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xF9, .codeLength = 16},
                                 {.type = RUNSIZECODE, .runSize = 0xFA, .codeLength = 16}};

uint16 dcLuminanceTable[12] = {0x00, 0x02, 0x03, 0x04, 0x05, 0x06, 0x0E, 0x1E, 0x3E, 0x7E, 0xFE, 0x1FE};
uint16 dcChrominanceTable[12] = {0x00, 0x01, 0x02, 0x06, 0x0E, 0x1E, 0x3E, 0x7E, 0xFE, 0x1FE, 0x3FE, 0x7FE};

uint16 acLuminanceTable[256] = {0x0A  , 0x00  , 0x01  , 0x04  , 0x0B  , 0x1A  , 0x78  , 0xF8  ,
                                0x3F6 , 0xFF82, 0xFF83, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0x0C  , 0x1B  , 0x79  , 0x1F6 , 0x7F6 , 0xFF84, 0xFF85,
                                0xFF86, 0xFF87, 0xFF88, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0x1C  , 0xF9  , 0x3F7 , 0xFF4 , 0xFF89, 0xFF8A, 0xFF8B,
                                0xFF8C, 0xFF8D, 0xFF8E, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0x3A  , 0x1F7 , 0xFF5 , 0xFF8F, 0xFF90, 0xFF91, 0xFF92,
                                0xFF93, 0xFF94, 0xFF95, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0x3B  , 0x3F8 , 0xFF96, 0xFF97, 0xFF98, 0xFF99, 0xFF9A,
                                0xFF9B, 0xFF9C, 0xFF9D, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0x7A  , 0x7F7 , 0xFF9E, 0xFF9F, 0xFFA0, 0xFFA1, 0xFFA2,
                                0xFFA3, 0xFFA4, 0xFFA5, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0x7B  , 0xFF6 , 0xFFA6, 0xFFA7, 0xFFA8, 0xFFA9, 0xFFAA,
                                0xFFAB, 0xFFAC, 0xFFAD, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0xFA  , 0xFF7 , 0xFFAE, 0xFFAF, 0xFFB0, 0xFFB1, 0xFFB2,
                                0xFFB3, 0xFFB4, 0xFFB5, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0x1F8 , 0x7FC0, 0xFFB6, 0xFFB7, 0xFFB8, 0xFFB9, 0xFFBA,
                                0xFFBB, 0xFFBC, 0xFFBD, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0x1F9 , 0xFFBE, 0xFFBF, 0xFFC0, 0xFFC1, 0xFFC2, 0xFFC3,
                                0xFFC4, 0xFFC5, 0xFFC6, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0x1FA , 0xFFC7, 0xFFC8, 0xFFC9, 0xFFCA, 0xFFCB, 0xFFCC,
                                0xFFCD, 0xFFCE, 0xFFCF, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0x3F9 , 0xFFD0, 0xFFD1, 0xFFD2, 0xFFD3, 0xFFD4, 0xFFD5,
                                0xFFD6, 0xFFD7, 0xFFD8, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0x3FA , 0xFFD9, 0xFFDA, 0xFFDB, 0xFFDC, 0xFFDD, 0xFFDE,
                                0xFFDF, 0xFFE0, 0xFFE1, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0x7F8 , 0xFFE2, 0xFFE3, 0xFFE4, 0xFFE5, 0xFFE6, 0xFFE7,
                                0xFFE8, 0xFFE9, 0xFFEA, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x00  , 0xFFEB, 0xFFEC, 0xFFED, 0xFFEE, 0xFFEF, 0xFFF0, 0xFFF1,
                                0xFFF2, 0xFFF3, 0xFFF4, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                0x7F9 , 0xFFF5, 0xFFF6, 0xFFF7, 0xFFF8, 0xFFF9, 0xFFFA, 0xFFFB,
                                0xFFFC, 0xFFFD, 0xFFFE, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  };

uint16 acChrominanceTable[256] = {0x00  , 0x01  , 0x04  , 0x0A  , 0x18  , 0x19  , 0x38  , 0x78  ,
                                  0x1F4 , 0x3F6 , 0xFF4 , 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x0B  , 0x39  , 0xF6  , 0x1F5 , 0x7F6 , 0xFF5 , 0xFF88,
                                  0xFF89, 0xFF8A, 0xFF8B, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x1A  , 0xF7  , 0x3F7 , 0xFF6 , 0x7FC2, 0xFF8C, 0xFF8D,
                                  0xFF8E, 0xFF8F, 0xFF90, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x1B  , 0xF8  , 0x3F8 , 0xFF7 , 0xFF91, 0xFF92, 0xFF93,
                                  0xFF94, 0xFF95, 0xFF96, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x3A  , 0x1F6 , 0xFF97, 0xFF98, 0xFF99, 0xFF9A, 0xFF9B,
                                  0xFF9C, 0xFF9D, 0xFF9E, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x3B  , 0x3F9 , 0xFF9F, 0xFFA0, 0xFFA1, 0xFFA2, 0xFFA3,
                                  0xFFA4, 0xFFA5, 0xFFA6, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x79  , 0x7F7 , 0xFFA7, 0xFFA8, 0xFFA9, 0xFFAA, 0xFFAB,
                                  0xFFAC, 0xFFAD, 0xFFAE, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x7A  , 0x7F8 , 0xFFAF, 0xFFB0, 0xFFB1, 0xFFB2, 0xFFB3,
                                  0xFFB4, 0xFFB5, 0xFFB6, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0xF9  , 0xFFB7, 0xFFB8, 0xFFB9, 0xFFBA, 0xFFBB, 0xFFBC,
                                  0xFFBD, 0xFFBE, 0xFFBF, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x1F7 , 0xFFC0, 0xFFC1, 0xFFC2, 0xFFC3, 0xFFC4, 0xFFC5,
                                  0xFFC6, 0xFFC7, 0xFFC8, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x1F8 , 0xFFC9, 0xFFCA, 0xFFCB, 0xFFCC, 0xFFCD, 0xFFCE,
                                  0xFFCF, 0xFFD0, 0xFFD1, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x1F9 , 0xFFD2, 0xFFD3, 0xFFD4, 0xFFD5, 0xFFD6, 0xFFD7,
                                  0xFFD8, 0xFFD9, 0xFFDA, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x1FA , 0xFFDB, 0xFFDC, 0xFFDD, 0xFFDE, 0xFFDF, 0xFFE0,
                                  0xFFE1, 0xFFE2, 0xFFE3, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x7F9 , 0xFFE4, 0xFFE5, 0xFFE6, 0xFFE7, 0xFFE8, 0xFFE9,
                                  0xFFEA, 0xFFEB, 0xFFEC, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x00  , 0x3FE0, 0xFFED, 0xFFEE, 0xFFEF, 0xFFF0, 0xFFF1, 0xFFF2,
                                  0xFFF3, 0xFFF4, 0xFFF5, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  ,
                                  0x3FA , 0x7FC3, 0xFFF6, 0xFFF7, 0xFFF8, 0xFFF9, 0xFFFA, 0xFFFB,
                                  0xFFFC, 0xFFFD, 0xFFFE, 0x00  , 0x00  , 0x00  , 0x00  , 0x00  };